---
functional:
  - Имя пользователя должно содержать от 3 до 16 символов
  - Пароль должен содержать от 6 до 16 символов
  - Подтверждение пароля должно совпадать с паролем
  - После успешной регистрации открывается главная страница сайта
  - После неправильно введенных значений в форме регистрации можно повторить попытку входа без перезагрузки страницы
  - Форма регистрации должна содержать поле Nickname, Email, Password, Password Confirmation, кнопку Submit, кнопки Sign in with Github, Sign with Discord
  - Форма входа для пользователей должна содержать поле Email, Password, кнопку Submit, кнопки Sign in with Github, Sign with Discord, Sign Up, Forgot your password?
  - На форме входа отображается ошибка если ввести неправильные почту или пароль
  - Если ввести неправильные значения в форме входа, то можно повторить попытку входа без перезагрузки страницы
  - После успешного входа открывается главная страница приложения
  - Сайт должен запоминать, что пользователь авторизован, при перезагрузке страницы пользователь должен оставаться авторизованным
  - При нажатии в шапке на Codebattle происходит переход на главную страницу
  - В шапке отображается количество онлайн пользователей и данные авторизованного пользователя
  - При нажатии на пользователя в шапке появляется выпадающее меню. В выпадающем меню кнопки My Profile, Settings, User ratings, Tasks? Tournaments, SourceCode, Hexlet, Join Discord, Tgcodebattle, Sign Out
  - На главной странице отображается Leaderboard за неделю, за месяц, за весь период с лимитом до 7 строк с пользователями
  - На главной странице отображается Lobby, Tournaments, History
  - При нажатии на LOBBY появляется таблица с 5 строками, столбцы Level, State, Players, Actions
  - При нажатии на TOURNAMENTS появляется 2 таблицы, Live tournaments и Completed tournaments
  - В таблице Live tournaments столбцы Title, Starts_at, Actions
  - В таблице Completed tournaments столбцы Title, Type, Starts_at, Actions
  - При нажатии на HISTORY появляется таблица со скороллом, столбцы Level, Players, Date, Actions
  - Внизу главной страницы отображается окно чата. Справа в окне отображаются онлайн пользователи и их количество. Есть возможность отправить личное сообщение или написать в группу.
  - На гланой странице отображается кнопка CREATE A GAME
  - При нажатии на кнопку CREATE A GAME открывается окно создания игры
  - В окне создания игры можно выбрать уровень сложности elementary, easy, medium, hard
  - В окне создания игры можно выбрать тип игры With other user, with a friend, with a bot
  - В окне создания игры можно выбрать продолжительность игры
  - В окне создания игры можно выбрать игру по названию или тегу
  - На странице игры отображается время до окнчания, поле с заданием, поле с выводом
  - На странице игры можно менять язык интерфейса с английского на русский, с русского на анлийский
  - На странице игры можно выбрать язык программирования, отображаются кнопки для проверки кода, сброса и кнопка сдаться
  - На странице игры можно менять тему редактора кода с темного на светлый и наоборот 
  - На странице игры можно включить редактор кода Vim
  - На странице игры должна быть подсказка для обучения пользователя
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
implicit:
  - Возможность изменять профиль: аватар, пароль, nickname
  - Возможностиь изменять язык
  - Возможность удалять аккаунт
